services:
  app:
    build: .
    working_dir: /app/
    command: ["/bin/sh", "wait.sh"]
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    env_file:
      - .env

  db:
    image: mysql:8.0
    ports:
      - "33900:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}